export const FocusTypes = {
	STRENGTH: 'STRENGTH',
	HYPERTROPHY: 'HYPERTROPHY',
	ENDURANCE: 'ENDURANCE'
};

export const ProgressionTypes = {
	WEEKLY: 'WEEKLY',
	DAILY: 'DAILY'
};

export const Weekdays = {
	MONDAY: 'MONDAY',
	TUESDAY: 'TUESDAY',
	WEDNESDAY: 'WEDNESDAY',
	THURSDAY: 'THURSDAY',
	FRIDAY: 'FRIDAY',
	SATURDAY: 'SATURDAY',
	SUNDAY: 'SUNDAY'
};

export const ParameterTypes = {
	TEST: 'TEST',
	NUMBER: 'NUMBER',
	PERCENT: 'PERCENT'
};

export const Exercises = {
	SQUAT: 'SQUAT',
	BENCH_PRESS: 'BENCH_PRESS',
	ROW: 'ROW',
	OVERHEAD_PRESS: 'OVERHEAD_PRESS',
	DEADLIFT: 'DEADLIFT'
};
